CREATE DATABASE [MemDemo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MemDemo', FILENAME = N'F:\SQL\Setupfiles\MemDemo.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB ), 
 FILEGROUP [MemFG] CONTAINS MEMORY_OPTIMIZED_DATA 
( NAME = N'MemData', FILENAME = N'F:\SQL\Setupfiles\MemData' )
 LOG ON 
( NAME = N'MemDemo_log', FILENAME = N'F:\SQL\Setupfiles\MemDemo_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [MemDemo] SET COMPATIBILITY_LEVEL = 140
GO
ALTER DATABASE [MemDemo] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MemDemo] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MemDemo] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MemDemo] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MemDemo] SET ARITHABORT OFF 
GO
ALTER DATABASE [MemDemo] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MemDemo] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MemDemo] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [MemDemo] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MemDemo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MemDemo] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MemDemo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MemDemo] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MemDemo] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MemDemo] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MemDemo] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MemDemo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MemDemo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MemDemo] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MemDemo] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MemDemo] SET  READ_WRITE 
GO
ALTER DATABASE [MemDemo] SET RECOVERY FULL 
GO
ALTER DATABASE [MemDemo] SET  MULTI_USER 
GO
ALTER DATABASE [MemDemo] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MemDemo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MemDemo] SET DELAYED_DURABILITY = DISABLED 
GO
USE [MemDemo]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [MemDemo]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [MemDemo] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO

--- Using memory-optimized tables
USE MemDemo
GO
CREATE TABLE dbo.MemoryTable
(id INTEGER NOT NULL PRIMARY KEY NONCLUSTERED HASH WITH (BUCKET_COUNT = 1000000),
 date_value DATETIME NULL)
WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_AND_DATA);

CREATE TABLE dbo.DiskTable
(id INTEGER NOT NULL PRIMARY KEY NONCLUSTERED,
 date_value DATETIME NULL);

 BEGIN TRAN
	DECLARE @Diskid int = 1
	WHILE @Diskid <= 500000
	BEGIN
		INSERT INTO dbo.DiskTable VALUES (@Diskid, GETDATE())
		SET @Diskid += 1
	END
COMMIT;

SELECT COUNT(*) FROM dbo.DiskTable;

BEGIN TRAN
	DECLARE @Memid int = 1
	WHILE @Memid <= 500000
	BEGIN
		INSERT INTO dbo.MemoryTable VALUES (@Memid, GETDATE())
		SET @Memid += 1
	END
COMMIT;

SELECT COUNT(*) FROM dbo.MemoryTable;

DELETE FROM DiskTable;
DELETE FROM MemoryTable;

SELECT o.Name, m.*
FROM
sys.dm_db_xtp_table_memory_stats m
JOIN sys.sysobjects o
ON m.object_id = o.id
